server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnet=true
    password: 123456

mybatis:
  # 打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl